### ISSUE TITLE
Make fonts bigger

### ISSUE THREAD

**Issue by keremkoseoglu** [keremkoseoglu/Jiraffe#17]

**Comment by cp-urvi-k** [comment]
@keremkoseoglu Hey, can i try this?

**Comment by keremkoseoglu** [comment]
@cp-urvi-k why not? Your pull request is more than welcome :)

**Comment by cp-urvi-k** [comment]
![Screenshot 2021-02-10 at 4 43 25 PM](https://user-images.githubusercontent.com/50900652/107502933-555cc200-6bbf-11eb-840a-d9a46c5ea700.png)
![Screenshot 2021-02-10 at 4 44 20 PM](https://user-images.githubusercontent.com/50900652/107502954-60175700-6bbf-11eb-95d8-a8f8ebca14ec.png)

@keremkoseoglu Please check the difference, Do you want to increase it more or it's ok?
I set font size: 20 , Please mention if you want different font size.

**Comment by keremkoseoglu** [comment]
@cp-urvi-k looks good to me, thanks! You can send your pull request. Thanks for the contribution.

**Comment by cp-urvi-k** [comment]
@keremkoseoglu Here is pull request. https://github.com/keremkoseoglu/Jiraffe/pull/18 :)

**Comment by keremkoseoglu** [comment]
@cp-urvi-k pull request approved and merged, thanks a lot for your kind contribution :)
